<?php
    use Illuminate\Support\Facades\Route;
    use App\Http\Controllers\Admin\AdminController;

    
    Route::get('/home', [AdminController::class, 'home'])->name('user.admin');
    Route::get('/admin_logout', [AdminController::class, 'logout'])->name('admin.logout');
    Route::get('/home/profile', [AdminController::class, 'profileUpdate'])->name('admin.profileUpdate');
    Route::post('/home/profile/data', [AdminController::class, 'updateProfileData'])->name('admin.updateProfileData');
    Route::get('/home/fee', [AdminController::class, 'fee'])->name('admin.fee');
    Route::get('/home/fee/add', [AdminController::class, 'addFee'])->name('admin.addFee');
    Route::post('/home/fee/submit', [AdminController::class, 'fee_submit'])->name('admin.fee_submit');
    Route::post('/home/fee/edit', [AdminController::class, 'editFee'])->name('admin.editFee');
    Route::post('/home/fee/edit/data', [AdminController::class, 'editFeeData'])->name('admin.editFeeData');
    Route::post('/home/fee/delete', [AdminController::class, 'deleteFee'])->name('admin.deleteFee');
    Route::get('/home/faculty', [AdminController::class, 'faculty'])->name('admin.faculty');
    Route::view('/home/add_faculty','addFaculty')->name('admin.addFaculty');
    Route::post('/home/add_faculty_create', [AdminController::class, 'createFaculty'])->name('createFaculty');
    Route::post('/home/faculty/edit', [AdminController::class, 'editFaculty'])->name('admin.editFaculty');
    Route::post('/home/faculty/edit/data', [AdminController::class, 'editFacultyData'])->name('editFacultyData');
    Route::post('/home/facultyDelete', [AdminController::class, 'facultyDelete'])->name('admin.facultyDelete');
    Route::get('/home/dean', [AdminController::class, 'deanHome'])->name('admin.dean');
    Route::get('/home/dean/add', [AdminController::class, 'addDean'])->name('admin.addDean');
    Route::post('/home/dean/create', [AdminController::class, 'deanCreate'])->name('admin.deanCreate');
    Route::post('/home/dean/edit', [AdminController::class, 'editDean'])->name('admin.editDean');
    Route::post('/home/dean/edit_data', [AdminController::class, 'deanEditData'])->name('admin.deanEditData');
    Route::post('/home/dean/delete', [AdminController::class, 'deanDelete'])->name('admin.deanDelete');
    Route::get('/home/hall', [AdminController::class, 'hall'])->name('admin.hall');
    Route::view('/home/hall/add', 'addHall')->name('admin.addHall');
    Route::post('/home/create', [AdminController::class, 'createHall'])->name('admin.createHall');
    Route::post('/home/hall/edit', [AdminController::class, 'editHall'])->name('admin.editHall');
    Route::post('/home/hall/edit_data', [AdminController::class, 'editHallData'])->name('admin.editHallData');
    Route::post('/home/hall_delete', [AdminController::class, 'deleteHall'])->name('admin.deleteHall');
    Route::get('/home/provost', [AdminController::class, 'provost'])->name('admin.provost');
    Route::get('/home/provost/add', [AdminController::class, 'addProvost'])->name('admin.addProvost');
    Route::post('/home/provost/create', [AdminController::class, 'provostCreate'])->name('admin.provostCreate');
    Route::post('/home/provost/edit', [AdminController::class, 'editProvost'])->name('admin.editProvost');
    Route::post('/home/provost/edit/data', [AdminController::class, 'editProvostData'])->name('admin.editProvostData');
    Route::post('/home/provost/delete', [AdminController::class, 'provostDelete'])->name('admin.provostDelete');
    Route::get('/home/controller', [AdminController::class, 'controller'])->name('admin.controller');
    Route::get('/home/controller/add', [AdminController::class, 'addController'])->name('admin.addController');
    Route::post('/home/controller/create', [AdminController::class, 'ControllerCreate'])->name('admin.ControllerCreate');
    Route::post('/home/controller/edit', [AdminController::class, 'editController'])->name('admin.editController');
    Route::post('/home/controller/edit/data', [AdminController::class,'editControllerData'])->name('admin.editControllerData');
    Route::post('/home/controller/delete', [AdminController::class,'deleteController'])->name('admin.deleteController');
    Route::get('/home/session', [AdminController::class, 'session'])->name('admin.session');
    Route::post('/home/add_session', [AdminController::class, 'addSession'])->name('admin.addSession');
    Route::get('/home/department', [AdminController::class, 'department'])->name('admin.department');
    Route::get('/home/department/add', [AdminController::class, 'addDepartmentView'])->name('admin.addDepartment');
    Route::post('/home/department/add', [AdminController::class, 'departmentCreate'])->name('admin.departmentCreate');
    Route::post('/home/department/edit', [AdminController::class, 'editDepartmentView'])->name('admin.editDepartment');
    Route::post('/home/department/edit_data', [AdminController::class, 'departmentEditData'])->name('admin.departmentEditData');
    Route::post('/home/department/delete', [AdminController::class, 'deleteDepartment'])->name('admin.deleteDepartment');
    Route::get('/home/chairman', [AdminController::class, 'chairmanHome'])->name('admin.chairman');
    Route::get('/home/chairman/add', [AdminController::class, 'ChairmanAdd'])->name('admin.addChairman');
    Route::post('/home/chairman/create', [AdminController::class, 'chairmanCreate'])->name('admin.chairmanCreate');
    Route::post('/home/chairman/edit', [AdminController::class, 'editChairman'])->name('admin.editChairman');
    Route::post('/home/chairman/edit_data', [AdminController::class, 'editChairmanData'])->name('admin.editChairmanData');
    Route::post('/home/chairman/delete', [AdminController::class, 'deleteChairman'])->name('admin.deleteChairman');
    Route::get('/home/account', [AdminController::class, 'account'])->name('admin.account');
    Route::get('/home/account/add', [AdminController::class, 'addAccount'])->name('admin.addAccount');
    Route::post('/home/account/create', [AdminController::class, 'createAccount'])->name('admin.createAccount');
    Route::post('/home/account/edit', [AdminController::class, 'editAccount'])->name('admin.editAccount');
    Route::post('/home/account/edit/data', [AdminController::class, 'editAccountData'])->name('admin.editAccountData');
    Route::post('/home/account/delete', [AdminController::class, 'deleteAccount'])->name('admin.deleteAccount');
    Route::get('/home/degree', [AdminController::class, 'degree'])->name('admin.degree');
    Route::get('/home/degree/add', [AdminController::class, 'addDegree'])->name('admin.addDegree');
    Route::post('/home/degree/create', [AdminController::class, 'createDegree'])->name('admin.createDegree');
    Route::post('/home/degree/edit', [AdminController::class, 'editDegree'])->name('admin.editDegree');
    Route::post('/home/degree/edit/data', [AdminController::class, 'editDegreeData'])->name('admin.editDegreeData');
    Route::post('/home/degree/delete', [AdminController::class, 'deleteDegree'])->name('admin.deleteDegree');
    Route::get('/home/special_degree', [AdminController::class, 'specialDegree'])->name('admin.specialDegree');
    Route::get('/home/special_degree/add', [AdminController::class, 'addSpecialDegree'])->name('admin.addSpecialDegree');
    Route::post('/home/special_degree/create', [AdminController::class, 'createSpecialDegree'])->name('admin.createSpecialDegree');
    Route::post('/home/special_degree/edit', [AdminController::class, 'editSpecialDegree'])->name('admin.editSpecialDegree');
    Route::post('/home/special_degree/edit/data', [AdminController::class, 'editSpecialDegreeData'])->name('admin.editSpecialDegreeData');
    Route::post('/home/special_degree/delete', [AdminController::class, 'deleteSpecialDegree'])->name('admin.deleteSpecialDegree');
    Route::get('/home/office_staff', [AdminController::class, 'officeStaff'])->name('admin.officeStaff');
    Route::get('/home/office_staff/add', [AdminController::class, 'addOfficeStaff'])->name('admin.addOfficeStaff');
    Route::post('/home/office_staff/create', [AdminController::class, 'officeStaffCreate'])->name('admin.officeStaffCreate');
    Route::post('/home/office_staff/delete', [AdminController::class, 'deleteOfficeStaff'])->name('admin.deleteOfficeStaff');
    Route::get('/home/professional_session', [AdminController::class, 'professionalSession'])->name('admin.professionalSession');
    Route::post('/home/professional_session/add', [AdminController::class, 'addProfessionalSession'])->name('admin.addProfessionalSession');
    Route::get('/home/hall_student_status', [AdminController::class, 'hallStudentStatus'])->name('admin.hallStudentStatus');
    Route::get('/home/hall_student_status/view', [AdminController::class, 'hallStatusView'])->name('admin.hallStatusView');
    Route::post('/home/hall_student_status/search', [AdminController::class, 'searchHallStudent'])->name('admin.searchHallStudent');
    Route::post('/home/hall_student_status/add', [AdminController::class, 'studentAddToHall'])->name('admin.studentAddToHall');
    Route::get('/home/hall_room', [AdminController::class, 'hallRoom'])->name('admin.hallRoom');
    Route::post('/home/hall_room/add', [AdminController::class, 'addHallRoom'])->name('admin.addHallRoom');
    Route::view('/home/admission_roll', 'studentAdmissionRoll')->name('admin.admissionRoll');
    Route::post('/home/admission_roll/add', [AdminController::class, 'addAdmissionRoll'])->name('admin.addAdmissionRoll');
    Route::get('/home/teacher', [AdminController::class, 'teacherHome'])->name('admin.teacherHome');
    Route::view('/home/teacher/add', 'addTeacher')->name('admin.addTeacher');
    Route::post('/home/teacher/create', [AdminController::class, 'TeacherCreate'])->name('admin.TeacherCreate');
    Route::post('/home/teacher/edit', [AdminController::class, 'editTeacher'])->name('admin.editTeacher');
    Route::post('/home/teacher/edit/data', [AdminController::class, 'editTeacherData'])->name('admin.editTeacherData');
    Route::post('/home/teacher/delete', [AdminController::class, 'teacherDelete'])->name('admin.teacherDelete');
    Route::get('/home/Exam_Registration', [AdminController::class, 'ExamRegistration'])->name('admin.ExamRegistration');
    Route::post('/home/exportRegistrationPdf', [AdminController::class, 'exportRegistrationPdf'])->name('admin.exportRegistrationPdf');
    Route::get('/home/admission_report', [AdminController::class, 'admissionReport'])->name('admin.admissionReport');
    Route::get('/home/hallCircular', [AdminController::class, 'hallCircular'])->name('admin.hallCircular');
    Route::post('/home/hallCircular/data', [AdminController::class, 'hallCircularData'])->name('admin.hallCircularData');
    Route::get('/home/circularView', [AdminController::class, 'circularView'])->name('admin.circularView');
    Route::view('/home/view_notices', 'viewNotices')->name('admin.view_notices');


